name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_action
          chmod 600 ~/.ssh/github_action
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          # Disable host key checking to prevent interactive prompt
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy to server
        run: |
          set -e  # Exit on any error
          ssh -i ~/.ssh/github_action sindfo@129.241.153.151 << 'EOF'
            cd /home/local/sindfo/repo/group4-webapp/frontend
            echo "Pulling latest code..."
            git pull
            echo "Installing dependencies..."
            npm install
            echo "Updating dependencies..."
            npm update
            echo "Building project..."
            npm run build
            echo "Stopping Next.js server..."
            ./killnextserver.sh
            cd /home/local/sindfo/repo/group4-webapp/backend
            echo "Restarting Spring Boot application..."
            ./restart-spring-boot.sh
            echo "Deployment finished."
            exit
          EOF
