name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_action
          chmod 600 ~/.ssh/github_action
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          # Disable host key checking to prevent interactive prompt
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/github_action sindfo@129.241.153.151 'cd /home/local/sindfo/repo/group4-webapp/frontend && git pull && npm install && npm run build && cd /home/local/sindfo/repo/group4-webapp/backend && ./restart-spring-boot.sh'
